version: "3"

services:
  api:
    container_name: aitranslate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - .env
    stdin_open: true
    tty: true